### ISSUE TITLE
Webpacker can't find application.js

### ISSUE THREAD

**Issue by Dorian** [BookOfGreg/react-rails-example-app#6]
I tried running the app, and going to `/welcome/index` I get:

```
Webpacker can't find application.js in /Users/d/src/clones/react-rails-example-app/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. Webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your Webpack configuration is not creating a manifest.
Your manifest contains:
{
}
````

**Comment by BookOfGreg** [comment]
Did you run `yarn` first?

```
Started GET "/welcome/index" for 127.0.0.1 at 2017-12-19 08:57:05 +0000
Processing by WelcomeController#index as HTML
  Rendering welcome/index.html.erb within layouts/application
[Webpacker] Compiling…
[Webpacker] Compiled all packs in /Users/e0052727/source/react-rails-example-app/public/packs
  Rendered welcome/index.html.erb within layouts/application (2542.7ms)
Completed 200 OK in 4256ms (Views: 4255.2ms)
```

**Comment by Dorian** [comment]
Thanks, running the commands fixed it, e.g. I got "Title: A working react component". Thanks

**Comment by BookOfGreg** [comment]
Glad I could help 👍

**Comment by acfunelas** [comment]
Hi! Sorry I'm new to this, may I ask how do I terminate spring? I tried running pkill spring but it doesnt seem to work

**Comment by BookOfGreg** [comment]
On most linux terminals you can use `ps aux` to list all processes. Then `kill -9 NUMBER` where the number is the PID on the row where spring is.

Of course if spring isn't there then it's not running so no need to kill it.
`pkill` on some linux systems is just a shortcut where you don't need to find the number by hand.

**Comment by acfunelas** [comment]
I am sorry. I failed to inform you that I am using windows as my operating system.

**Comment by BookOfGreg** [comment]
@acfunelas if you're using a windows cmd or powershell prompt then you should still be able to run `spring stop` as a command. If that fails, you could check your processes in task manager, but other than that I do not know how to help you further.
I'd always recommend developing on Linux where possible unless you specifically need Windows as part of your workflow.
